=== Orochimarufan/Kawariki/versions.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://github.com/Orochimarufan/Kawariki/versions.schema.json",
    "title": "Distributions",
    "description": "Describes different distributions/versions of an engine component",
    "definitions": {
        "interpolated_string": {
            "description": "String interpolated with adjacent values using python {key} syntax",
            "type": "string"
        },
        "pattern_string": {
            "description": "Interpolated String that can be selected from multiple options",
            "oneOf": [
                {
                    "$ref": "#/definitions/interpolated_string"
                },
                {
                    "type":"object",
                    "patternProperties": {
                        "[^=]+!?=.+": {
                            "$ref": "#/definitions/pattern_string"
                        },
                        "": {
                            "$ref": "#/definitions/pattern_string"
                        }
                    },
                    "additionalProperties": false,
                    "minProperties": 1
                }
            ]
        },
        "value": {
            "description": "Value that can be selected from multiple options",
            "oneOf": [
                {
                    "$ref": "#/definitions/interpolated_string"
                },
                {
                    "type": "object",
                    "patternProperties": {
                        "[^=]+!?=.+": {
                            "$ref": "#/definitions/value"
                        },
                        "": {
                            "$ref": "#/definitions/value"
                        }
                    },
                    "additionalProperties": false,
                    "minProperties": 1
                },
                {
                    "type": "boolean"
                },
                {
                    "type": "number"
                },
                {
                    "type": "array",
                    "items": {"$ref": "#/definitions/value"}
                }
            ]
        },
        "info": {
            "type": "object",
            "properties": {
                "template": {
                    "description": "Template to extend from. Must be plain string. (v3+)",
                    "type": "string"
                },
                "name": {
                    "description": "Human-readable name of the distribution",
                    "$ref": "#/definitions/interpolated_string"
                },
                "alias": {
                    "description": "Names a distribution may be referred to by for selecting it explicitly",
                    "type":"array",
                    "items": {"$ref": "#/definitions/interpolated_string"}
                },
                "version": {
                    "description": "The version number as array of integers. Trailing element may be a string",
                    "type": "array",
                    "items": {
                        "oneOf": [
                            {"type": "integer"},
                            {"type": "string"}
                        ]
                    },
                    "minItems": 2
                },
                "platforms": {
                    "description": "The list of supported platform strings",
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1
                },
                "slug": {
                    "description": "A slug to use when generating filesystem paths. Also an implicit unique alias value",
                    "$ref": "#/definitions/pattern_string"
                },
                "binary": {
                    "description": "The binary filename relative to the extracted distribution",
                    "$ref": "#/definitions/pattern_string"
                },
                "url": {
                    "description": "The URL to download the distribution from",
                    "$ref": "#/definitions/pattern_string"
                },
                "strip_leading": {
                    "description": "Strip the leading component from the extracted files",
                    "oneOf": [
                        {"type": "boolean"},
                        {"type": "string"}
                    ]
                }
            },
            "additionalProperties": {
                "$ref": "#/definitions/value"
            }
        }
    },
    "type":"object",
    "properties": {
        "$schema": {
            "type":"string"
        },
        "format": {
            "type": "integer",
            "description": "Format version number, currently 3"
        },
        "name": {
            "description": "Component name",
            "type": "string"
        },
        "platforms": {
            "type": "object",
            "description": "Mapping Kawariki platform strings to distribution platform strings, if necessary",
            "additionalProperties": {
                "type": "string"
            },
            "minProperties": 1
        },
        "common": {
            "description": "Properties common to all versions (v2)",
            "$ref": "#/definitions/info"
        },
        "templates": {
            "description": "Template definitions (v3+)",
            "type": "object",
            "properties": {
                "": {
                    "description": "Default template that is always applied last",
                    "$ref": "#/definitions/info",
                    "dependencies": {
                        "template": false
                    }
                }
            },
            "additionalProperties": {
                "$ref": "#/definitions/info"
            }
        },
        "versions": {
            "description": "The available versions of the component",
            "type": "array",
            "items": {
                "$ref": "#/definitions/info"
            },
            "minItems": 1
        }
    },
    "required": ["format", "name", "versions"],
    "additionalProperties": false,
    "dependencies": {
        "common": {
            "properties": {
                "format": {
                    "enum": [2]
                }
            }
        },
        "templates": {
            "properties": {
                "format": {
                    "enum": [3]
                }
            }
        }
    }
}

=== Orochimarufan/Kawariki/renpy/versions.json
{
    "$schema": "../versions.schema.json",
    "format": 2,
    "name": "renpy",
    "common": {
        "name": "Ren'Py SDK v{version!v}",
        "binary": "renpy.sh",
        "slug": "renpy-sdk-{version!v}-intel",
        "platforms": ["linux-x86_64", "linux-i686", "darwin-x86_64"],
        "url": "https://www.renpy.org/dl/{version!v}/renpy-{version!v}-sdk.tar.bz2",
        "strip_leading": "renpy-"
    },
    "versions": [
        {
            "alias": ["8", "py3"],
            "version": [8, 1, 3]
        },
        {
            "version": [8, 0, 3]
        },
        {
            "alias": ["7", "py2"],
            "version": [7, 6, 3]
        },
        {
            "version": [7, 5, 3]
        }
    ]
}
